- name: copy catalogue service to system directory
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: systemctl daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable the catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted ##Even app is not running we can restart
    enabled: yes
